### ISSUE TITLE
Excuse me, I use scissors to destroy the grass, and I can’t get the grass items

### ISSUE THREAD

**Issue by tangzixiang-hash** [Wimpingego/nnow#10]
I am using the 1.16.5-1.0.8 version. I tested it and only used this mod. After obtaining the scissors, I used the scissors to destroy the grass without any falling objects.
may I ask if this is normal.

**Comment by Wimpingego** [comment]
Hi Tangzixiang-hash , By **scissors** I'm taking it you mean **shears** and they should work like iron shear do that are already in the base game. I have tested **NNOW 1.16.5-1.0.8** with **Forge 36.0.14** in **Minecraft 1.16.5** and they seem to be working fine. If you can give me more information I can see if I can get them to not work like they are for you but for me they look to be all good.

**Comment by tangzixiang-hash** [comment]
I ran some tests afterwards
Using the original scissors to destroy grass cannot obtain grass items, but destroying leaves can obtain leaves
Using the scissors provided by this mod to destroy grass can obtain grass, but destroying leaves cannot obtain leaves.

**Comment by Wimpingego** [comment]
I have posted a new update which I hope fixes this bug
