### ISSUE TITLE
I made a chinese lang

### ISSUE THREAD

**Issue by SmallJiJi** [Wimpingego/nnow#12]
please use it
zh_cn
{	
	"itemGroup.NNOWTab": "未曾设想的物品",
	
	"item.nnow.redstone_nugget": "红石粒",
	"item.nnow.glowstone_nugget": "荧石粒",	
	"item.nnow.lapis_nugget": "青金石粒",
	"item.nnow.quartz_nugget": "石英粒",
	"item.nnow.diamond_nugget": "钻石粒",
	"item.nnow.netherite_nugget": "下界合金粒",
	"item.nnow.emerald_nugget": "绿宝石粒",
	"item.nnow.coal_nugget": "煤炭粒",
	"item.nnow.ice_nugget": "冰粒",
	"item.nnow.fire_nugget": "岩浆粒",
	"item.nnow.wooden_nugget": "木粒",
	
	"item.nnow.copper_nugget": "铜粒",
	"item.nnow.nickel_nugget": "镍粒",
	"item.nnow.silver_nugget": "银粒",
	"item.nnow.uranium_nugget": "铀粒",
	"item.nnow.lead_nugget": "铅粒",
	"item.nnow.aluminum_nugget": "铝粒",	
	"item.nnow.tin_nugget": "锡粒",
	"item.nnow.osmium_nugget": "锇粒",	
	"item.nnow.bismuth_nugget": "铋粒",	
	"item.nnow.zinc_nugget": "锌粒",
	"item.nnow.platinum_nugget": "铂粒",	
	"item.nnow.iridium_nugget": "铱粒",		

	"item.nnow.copper_ingot": "铜锭",
	"item.nnow.nickel_ingot": "镍锭",
	"item.nnow.silver_ingot": "银锭",
	"item.nnow.uranium_ingot": "铀锭",
	"item.nnow.lead_ingot": "铅锭",
	"item.nnow.aluminum_ingot": "铝锭",
	"item.nnow.tin_ingot": "锡锭",
	"item.nnow.osmium_ingot": "锇锭",
	"item.nnow.bismuth_ingot": "铋锭",	
	"item.nnow.zinc_ingot": "锌锭",
	"item.nnow.platinum_ingot": "铂锭",			
	"item.nnow.iridium_ingot": 铱锭",	

	"item.nnow.bun_in_the_oven": "有喜了",
	
	"item.nnow.weetabix": "维他麦",
	"item.nnow.bowl_of_weetabix": "一碗维他麦",

	"item.nnow.stone_dust": "石头粉末",
	"item.nnow.sand_dust": "沙子粉尘",
	"item.nnow.dirt_dust": "土尘",
	"item.nnow.gravel_dust": "沙粒粉尘",
	"item.nnow.clay_dust": "粘土粉",
	
	"item.nnow.stone_hammer": "石锤",
	"item.nnow.iron_hammer": "铁锤",
	"item.nnow.golden_hammer": "金锤",
	"item.nnow.diamond_hammer": "钻石锤",
	"item.nnow.netherite_hammer": "下界合金锤",	
	"item.nnow.emerald_hammer": "绿宝石锤",
	
	"item.nnow.stone_spade": "石铲",
	"item.nnow.iron_spade": "铁铲",
	"item.nnow.golden_spade": "金铲",
	"item.nnow.diamond_spade": "钻石铲",
	"item.nnow.netherite_spade": "下界合金铲",
	"item.nnow.emerald_spade": "绿宝石铲",

	"item.nnow.wooden_shears": "木剪刀",
	"item.nnow.golden_shears": "金剪刀",
	"item.nnow.diamond_shears": "钻石剪刀",
	"item.nnow.netherite_shears": "下界合金剪刀",	

	"item.nnow.bundle_leaves": "Bundle Of Leaves",
	
	"item.nnow.magnet": "强力磁铁",
	"item.nnow.magnet.line1": "磁铁已激活：%s",
	"item.nnow.magnet.line2": "在玩家物品栏中工作",
	"item.nnow.magnet.line3": "吸引范围：%s",
	
	"item.nnow.viagra": "村民激烈区域生长范围附件",
	"item.nnow.viagra.line1": "只在你的主手上工作",
	"item.nnow.viagra.line2": "影响半径：%s",
	"item.nnow.viagra.line3": "强烈运作中：%s",
	
	"item.nnow.poking_stick": "平皱棒",
	"item.nnow.stone_poking_stick": "石制平皱棒",
	"item.nnow.iron_poking_stick": "铁制平皱棒",
	"item.nnow.poking_stick.line1": "不知道这玩意用来干啥，但为什么不试试用它刨点东西？",

	"item.nnow.death_potato": "死亡马铃薯",
	"item.nnow.ender_bag": "末影袋",	
	
	"item.nnow.doom_disc": "音乐唱片",
	"item.nnow.doom_disc.desc": "Tremble Mortals - Doom is HERE",
	"item.doom_disc.sub": "Doom Music",
	
	"item.nnow.mizzy_disc": "音乐唱片",
	"item.nnow.mizzy_disc.desc": "Pink & Fluffy - Dancing on rainbows",
	"item.mizzy_disc.sub": "Mizzy Music",

	"item.nnow.clear_leather_helmet": "隐形皮革帽子",
	"item.nnow.clear_iron_helmet": "隐形铁头盔",
	"item.nnow.clear_golden_helmet": "隐形金头盔",
	"item.nnow.clear_diamond_helmet": "隐形钻石头盔",
	"item.nnow.clear_chain_helmet": "隐形锁链头盔",
	"item.nnow.clear_turtle_helmet": "隐形海龟壳",
	"item.nnow.clear_netherite_helmet": "隐形下界合金头盔",
	
	"block.nnow.end_lantern": "末影珍珠",

	"block.nnow.iron_trap": "铁陷阱",
	"block.nnow.gold_trap": "金陷阱",
	"block.nnow.diamond_trap": "钻石陷阱",
	"block.nnow.wither_trap": "防凋零陷阱",
	"block.nnow.monster_trapper_poi": "老旧的陷阱",
	
	"block.nnow.old_derpy_poi": "石中剑",
	"block.nnow.beekeeper_poi": "蜂箱维修台",	
	"block.nnow.banker_poi": "会计桌",	
	"block.nnow.end_trader_poi": "末影转运箱",	
	"block.nnow.sea_fisherman_poi": "渔架",
	"block.nnow.sea_trader_poi": "市场摊位",	
	"block.nnow.nether_trader_poi": "死去的僵尸猪灵",
	"block.nnow.ingot_trader_poi": "损坏的高炉",	
	
	"block.nnow.agg_block": "反重力沙砾",
	"block.nnow.ags_block": "反重力沙子",
	"block.nnow.agrs_block": "反重力红沙",
	"block.nnow.dark_glass_block": "暗黑玻璃",
	"block.nnow.super_obsidian": "超级黑曜石",
	"block.nnow.super_obsidian_bars": "超级黑曜石栏杆",
	"block.nnow.hydrotank": "水箱",
	"block.nnow.hydrotank_light": "亮水箱",
		
	"block.nnow.waterwell": "水泵",
	"block.nnow.lavawell": "岩浆泵",	
	"block.nnow.cobblegen": "刷石机",	

	"block.nnow.cauldron_acacia": "金合欢木炼药锅",
	"block.nnow.cauldron_birch": "白桦木炼药锅",
	"block.nnow.cauldron_dark_oak": "深色橡木炼药锅",
	"block.nnow.cauldron_jungle": "丛林木炼药锅",
	"block.nnow.cauldron_oak": "橡木炼药锅",
	"block.nnow.cauldron_spruce": "云杉木炼药锅",	
	
	"block.nnow.grass_slab": "玻璃台阶",	
	"block.nnow.gravel_slab": "沙砾台阶",
	"block.nnow.sand_slab": "沙子台阶",
	"block.nnow.redsand_slab": "红沙台阶",
	"block.nnow.coarsedirt_slab": "砂土台阶",	
	"block.nnow.dirt_slab": "泥土台阶",
	"block.nnow.path_slab": "草径台阶",	
	"block.nnow.cracked_stone_bricks_slab": "裂石砖台阶",	
	"block.nnow.bookshelf_slab": "书架台阶",
	
	"block.nnow.oak_leaves_slab": "橡树树叶台阶",	
	"block.nnow.dark_oak_leaves_slab": "深色橡树树叶台阶",
	"block.nnow.jungle_leaves_slab": "丛林树叶台阶",
	"block.nnow.acacia_leaves_slab": "金合欢树叶台阶",
	"block.nnow.spruce_leaves_slab": "云杉树叶台阶",	
	"block.nnow.birch_leaves_slab": "白桦树叶台阶",

	"block.nnow.gravel_stairs": "沙砾楼梯",
	"block.nnow.sand_stairs": "沙子楼梯",	
	"block.nnow.redsand_stairs": "红沙楼梯",		
	"block.nnow.coarsedirt_stairs": "砂土楼梯",		
	"block.nnow.dirt_stairs": "泥土楼梯",	
	"block.nnow.cracked_stone_bricks_stairs": "裂石砖楼梯",	
	"block.nnow.bookshelf_stairs": "书架楼梯",
	
	"block.nnow.oak_leaves_stairs": "橡树树叶楼梯",	
	"block.nnow.dark_oak_leaves_stairs": "深色橡树树叶楼梯",
	"block.nnow.jungle_leaves_stairs": "丛林树叶楼梯",
	"block.nnow.acacia_leaves_stairs": "金合欢树叶楼梯",
	"block.nnow.spruce_leaves_stairs": "金合欢树叶楼梯",	
	"block.nnow.birch_leaves_stairs": "白桦树叶楼梯",	
		
	"block.nnow.iron_berry_bush": "铁浆果",
	"block.nnow.gold_berry_bush": "金浆果",
	"block.nnow.coal_berry_bush": "煤浆果",
	"block.nnow.redstone_berry_bush": "红石浆果",
	"block.nnow.glowstone_berry_bush": "萤石浆果",	
	"block.nnow.lapis_berry_bush": "青金石浆果",
	"block.nnow.quartz_berry_bush": "石英浆果",
	"block.nnow.emerald_berry_bush": "绿宝石浆果",
	"block.nnow.diamond_berry_bush": "钻石浆果",
	"block.nnow.netherite_berry_bush": "下界合金浆果",	
	"block.nnow.ice_berry_bush": "冰浆果",
	"block.nnow.xp_berry_bush": "经验浆果",
	"block.nnow.fire_berry_bush": "岩浆浆果",
	"block.nnow.wooden_berry_bush": "木浆果",
	"block.nnow.stone_berry_bush": "石浆果",
	"block.nnow.sand_berry_bush": "沙浆果",
	"block.nnow.clay_berry_bush": "粘土浆果",
	"block.nnow.dirt_berry_bush": "泥土浆果",
	"block.nnow.gravel_berry_bush": "沙砾浆果",
	
	"block.nnow.copper_berry_bush": "铜浆果",
	"block.nnow.nickel_berry_bush": "镍浆果",
	"block.nnow.silver_berry_bush": "银浆果",
	"block.nnow.uranium_berry_bush": "铀浆果",
	"block.nnow.lead_berry_bush": "铅浆果",
	"block.nnow.aluminum_berry_bush": "铝浆果",
	"block.nnow.tin_berry_bush": "锡浆果",
	"block.nnow.osmium_berry_bush": "锇浆果",
	"block.nnow.bismuth_berry_bush": "铋浆果",
	"block.nnow.zinc_berry_bush": "锌浆果",
	"block.nnow.platinum_berry_bush": "铂浆果",
	"block.nnow.iridium_berry_bush": "铱浆果",
	
	"block.nnow.copper_block": "铜块",
	"block.nnow.nickel_block": "镍块",
	"block.nnow.silver_block": "银块",
	"block.nnow.uranium_block": "铀块",
	"block.nnow.lead_block": "铅块",
	"block.nnow.aluminum_block": "铝块",
	"block.nnow.tin_block": "锡块",
	"block.nnow.osmium_block": "锇块",
	"block.nnow.bismuth_block": "铋块",
	"block.nnow.zinc_block": "锌块",
	"block.nnow.platinum_block": "铂块",	
	"block.nnow.iridium_block": "铱块",	
	
	"block.nnow.end_cake": "末地蛋糕",
	"block.nnow.nether_cake": "下界蛋糕",	
	"block.nnow.overworld_cake": "主世界蛋糕",	
	
	"entity.minecraft.villager.nnow.old_derpy": "老流氓",
	"entity.minecraft.villager.nnow.banker": "会计师",
	"entity.minecraft.villager.nnow.beekeeper": "养蜂人",
	"entity.minecraft.villager.nnow.monster_trapper": "Monster Trapper",
	"entity.minecraft.villager.nnow.end_trader": "末地商人",
	"entity.minecraft.villager.nnow.sea_fisherman": "渔夫",
	"entity.minecraft.villager.nnow.sea_trader": "海洋商人",
	"entity.minecraft.villager.nnow.nether_trader": "下界商人",
	"entity.minecraft.villager.nnow.ingot_trader": "合金锭商人",	

	"item.nnow.hydrotank.line1": "为你的农田提供水源",
	"item.nnow.hydrotank.line2": "但下方无需方块阻挡水流",
	"item.nnow.hydrotank.line3": "方块拥有有15级亮度",	

	"item.nnow.cobblegen.line1": "圆石的生产源",
	"item.nnow.cobblegen.general.line1": "用镐子右键此方块",	
	
	"item.nnow.waterwell.line1": 无尽的水源",
	"item.nnow.waterwell.general.line1": "用空桶右键此方块",	
	
	"item.nnow.lavawell.line1": "无尽的岩浆",
	"item.nnow.lavawell.general.line1": "用空桶右键此方块",
	
	"item.nnow.IronTrap.line1": "陷阱每次对生物进行1点伤害",
	"item.nnow.GoldTrap.line1": "陷阱可以杀死生物",
	"item.nnow.DiamondTrap.line1": "陷阱可以杀死生物饼让玩家掉下来",
	"item.nnow.witherproof.line1": "防凋零",
	
	"item.nnow.hammer.line1": "大范围挖掘方块",
	"item.nnow.hammer.line2": "范围为3x3",
		
	"item.nnow.spade.line1": "大范围挖掘方块",
	"item.nnow.spade.line2": "范围为3x3",
	
	"item.nnow.ender_bag.line1": "末影袋",
	
	"nnow.cake.reset.complete": "在%s维度保存的位置已经复位",
    "nnow.cake.reset.failed": "并没有在%s维度保存任何位置",
	
  	"death.attack.trap.iron": "铁陷阱刺穿了%s",
  	"death.attack.trap.gold": "金陷阱刺穿了%s",
  	"death.attack.trap.diamond.player": "钻石陷阱刺穿了%ss",
  	"death.attack.trap.wither.player": "防凋零陷阱刺穿了%s"
	
}

**Comment by ChromaPIE** [comment]
Don't take it. Contains thousands of errors. Nonstandard and poorly made work guaranteed from a veteran minecraft mod enus2zhcn translator and native Chinese speaker. I'll make mine in a pull request when this issue gets closed.

**Comment by SmallJii** [comment]
> 别拿了包含数千个错误。非标准和制作不良的工作保证从一个老矿工艺mod enus2zhcn翻译和母语中文。如果符合外线方面的要求，当此问题被关闭时，我将提出我的拉取请求。

emm，的确是挺劣质的。。。挺抱歉的，主要是没有其他人翻译就自己上了。。。
但还是挺想快点拿到有翻译的模组的。。。你那边能不能快点传一下。。。（应该都是中国人直接有中文交流了）

**Comment by SmallJii** [comment]
> Don't take it. Contains thousands of errors. Nonstandard and poorly made work guaranteed from a veteran minecraft mod enus2zhcn translator and native Chinese speaker. I'll make mine in a pull request if it fits what the officail side's want, when this issue gets closed.

主要怪在我英文太差了哈哈哈XD
