### ISSUE TITLE
Berries do not work with tested auto farming machines

### ISSUE THREAD

**Issue by InflamedSebi** [Wimpingego/nnow#2]
Hey. I tried auto farming the berry bushes, which did not work.  I got the closest results with [Create Harvesters](https://www.curseforge.com/minecraft/mc-mods/create) since they do detect the bushes as harvestable plants and they do harvest them correctly, but they so not get any drops from it.
I also tried some other farming mods (industrial foregoing/straw golem) which did not work either.
Maybe you can have a look at this :)

**Comment by Wimpingego** [comment]
They have been added to Immersive Engineering cloche and Botany Pots in the next update, I will take a look at the other soon
