### ISSUE TITLE
[Bug] Spade and Hammer weirdness

### ISSUE THREAD

**Issue by drakray** [Wimpingego/nnow#6]
Minecraft 1.16.3
Forge .25
NeverNeededOrWanted-1.16.3-1.0.4

Spade drop Clay Dust on Dirt block, and drop dirt on grass block
Hammer mine Dirt, Sand and Gravel, drop block, but correctly not mine grass block
Hammer drop block version instead of dust?

**Comment by drakray** [comment]
Gravel drop sand dust
Sand drop Dirt dust
Clay drop clay ball

**Comment by Calibos** [comment]
This is good behavior. This is so you can start with cobble and get gravel, sand, dirt, and clay in a skyblock.

**Comment by drakray** [comment]
is it possible to have a config so that blocks drop their own dust instead?

**Comment by Calibos** [comment]
what is the purpose of this?

**Comment by drakray** [comment]
normal map large scale excavating
right now I tried to use a Spade to mine gravel to make path, but instead got sand, so pretty useless in this endeavor

**Comment by Calibos** [comment]
use the emerald hammer for 3x3 mining

**Comment by drakray** [comment]
it's classified as a pickaxe; even though it doesn't use more durability when mining shovel-block, it get the speed penalty
also, pretty counter-intuitive, as the Spade can't be used on pickaxe-block

**Comment by Calibos** [comment]
spade should be shovel base so dirt, gravel, sand 

hammer, for cobble and stone

**Comment by drakray** [comment]
I know that, that's what I said
When I use Spade to shovel dirt, gravel, or sand, they do not drop their respective dust as they should, and if it is by design, I think it would be beneficial to have a config to make it behave this way.
Right now it is impossible to get Gravel when using a Spade, and I have so much Clay I could pave 3 villages in bricks.

When I use Hammer to mine stone, I get cobblestone as with a normal pickaxe, whereas I think it should drop Stone Dust to keep consistency with the Spade.
If I use the Hammer on a block of Cobble or Stone, surrounded by Dirt, the dirt will be broken to they block version, instead of being ignore, as is the case if the stone is surrounded by grass block.

**Comment by Calibos** [comment]
emerald spade and hammer drop base blocks, any of the other hammer and spade, tiers should drop respective dusts of whatever the next tier item is, surrounding blocks shouldn't matter, looking into it, what hammer/spade are you using? emerald or one of the lower tiers?

**Comment by drakray** [comment]
diamond spade, emerald hammer
I'll test with stone spade and stone hammer, and with emerald spade

**Comment by Calibos** [comment]
yeah, emerald spade should solve your problem it sounds
diamond spade breaks down to next tier, emerald spade does not

**Comment by drakray** [comment]
Emerald hammer drop cobblestone normally, but still mine dirt, gravel and sand. it does not mine grass block
Emerald Spade drop dirt, gravel and sand
Stone and Diamond hammer drop the "tiered dust" of soft block surrounding the mined stone

It indeed seems like the feature I want is the emerald tools; mine to get the block
The lower tier hammer mining soft block is a bug though I think, even if they mine to dust

**Comment by Calibos** [comment]
it is ok for the hammer to mine the soft tiers, not a bug

**Comment by drakray** [comment]
ok, that's weird, but if it's by design, 🤷
