### ISSUE TITLE
Crash placing Path Slab

### ISSUE THREAD

**Issue by Pentasis** [Wimpingego/nnow#8]
Minecraft crashes when I try to place a path slab on another path slab:
https://paste.ee/p/DojSL

MC 1.16.3
Forge 34.1.40
nnow 1.0.4

**Comment by Wimpingego** [comment]
Are you playing a custom pack of your own making or someone else's if so can I have the name of the pack because loading NNOW 1.0.4 by its self in forge 34.1.40 or higher does not crash.

**Comment by Pentasis** [comment]
Its a custom pack. Not sure how to make a good modlist for you but I tried: https://pastebin.com/4udFEBJY

**Comment by Pentasis** [comment]
Just to make sure I was clear: I tried placing both slabs in the same blockspace.

**Comment by Wimpingego** [comment]
If your using the twitch launcher can you export the profile for me and send it me if that not to much trouble?, So making it a double slab right ?

**Comment by Pentasis** [comment]
https://1drv.ms/u/s!AjpiLXE9V1Flh4omXH7Qj6CaBgLigw?e=D1p44r
I use twitch to download mods, but actually play with MultiMC, so I hope this works.
Yes, a double slab.

**Comment by Wimpingego** [comment]
That's cool, I will download the zip and take a look around thanks for that. I will keep you updated I just have to pop out in a min but will get to it as soon as I can.

**Comment by Pentasis** [comment]
No hurries, take your time.

**Comment by Calibos** [comment]
bad interaction with the mod 'doubleslabs'

**Comment by Pentasis** [comment]
Does this mean I need to report this with the doubleslabs mod; is the bug in their code?

**Comment by Wimpingego** [comment]
The bug is on there end not mine from the looks of it as all my slabs are coded the same way and it's only the path block that crashes. Like Calibos said the crash point to doubleslabs being the issue. I looking at a quick fix in a few mins as I should be able to push it out to fix it for you.

**Comment by Pentasis** [comment]
I can live without the double slab mod and will disable it, there are other solutions for that. I'll report the bug on their issue tracker; if it isn't already there. Thank you for your time and effort.

**Comment by Wimpingego** [comment]
No need to remove Double Slabs I have load uploaded a quick fix to Cruse now and it should be live soon.
