### ISSUE TITLE
Suggestion: Add Glowstone Berry bushes

### ISSUE THREAD

**Issue by SamhitApple** [Wimpingego/nnow#9]
Since there is even wood berry bush variant, I think the only missing one is glowstone berries! Glowstone dust is especially very useful to make fuelium to power vehicles in Mr.Crayfish's Vehicle Mod, so please consider adding it!

**Comment by Wimpingego** [comment]
Good idea, I think the reason I didn't add it at the time was because you can get it from one of the new villagers but a bush could be something that can be added.

**Comment by SamhitApple** [comment]
Oh, thank you in advance now that you're gonna add it!

**Comment by Wimpingego** [comment]
It will most likely be for 1.16.4 and up that I do add it to.

**Comment by SamhitApple** [comment]
Thank you! I see you've updated the mod! PS: I use 1.16.4, so NP!
